meta:
  configurationVersion: 0.1
  released: 2019-05-17

qudiniAppStaticData:
  baseuri: http://localhost:8080
  user: "sysadmin"
  password: "Passphrase01"

requestStaticValues:
  defaultCharSet: "UTF-8"

