meta:
  configurationVersion: 0.1
  released: 2019-05-17

qudiniAppStaticData:
  baseuri: http://localhost:8080
  user: "add_your_user_here"
  password: "add_your_pass_here"

requestStaticValues:
  defaultCharSet: "UTF-8"

